In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Proyecto/docentes_RAW.csv')

In [4]:
df.shape

(169, 5)

In [5]:
df.columns

Index(['DOCENTE', 'ASIGNATURAS', 'GRUPO', 'HORAS', 'COMPONENTE'], dtype='object')

In [6]:
df.tail()

,DOCENTE,ASIGNATURAS,GRUPO,HORAS,COMPONENTE
164,MÓDULO,módulo iv. diseña y gestiona bases de datos of...,5B,NaN,Módulo
165,MÓDULO,módulo iv. diseña y gestiona bases de datos of...,5F,NaN,Módulo
166,MÓDULO,módulo iv. diseña y mantiene los sistemas de i...,5D,NaN,Módulo
167,MÓDULO,"módulo iv. mantiene equipos hidráulicos, neumá...",5E,NaN,Módulo
168,MÓDULO,"módulo iv. mantiene equipos hidráulicos, neumá...",5H,NaN,Módulo

In [7]:
df.dtypes

DOCENTE         object
ASIGNATURAS     object
GRUPO           object
HORAS          float64
COMPONENTE      object
dtype: object

In [8]:
df_docentes = df['DOCENTE'].str.title()
df_docentes_unicos = df_docentes.unique()
df_docentes_unicos = pd.DataFrame({'DOCENTES': df_docentes_unicos})

In [9]:
df['DOCENTE'] = df_docentes
df_docentes_unicos

                                 DOCENTES
0           Garcia Hernandez Luis Eduardo
1               Ramirez Perez Juana Maria
2          Lopez Rodriguez Antonio Manuel
3           Lopez Rodriguez Antonia Maria
4             Gutierrez Lopez Pedro Pablo
5             Rodriguez Garcia Ana Carmen
6         Velazquez Hernandez Maria Elena
7            Garcia Ruiz Francisco Javier
8             Velazquez Hernandez Luciana
9          Gutierrez Martinez Pedro Pablo
10        Mendoza Hernandez Jorge Alberto
11        Hernandez Garcia Fabian Enrique
12        Garcia Hernandez Fabian Enrique
13             Ruiz Gutierrez Maria Sofia
14            Lopez Ramirez Marco Antonio
15               Gonzalez Lopez Ana Luisa
16                  Garcia Alvarez Andres
17            Ramirez Lopez Maria Dolores
18           Ramirez Gonzalez Pedro Pablo
19       Martinez Villasenor Luis Eduardo
20        Rodriguez Alatorre Ana Patricia
21          Hernandez Reyes Daniela Sofia
22         Reyes Rodriguez Antonio Rafael
23      Verduzco Morales Fabian Alexander
24      Reyes Rodriguez Esteban Alejandro
25            Garcia Llamas Liliana Maria
26           Reyes Rodriguez Antonio Raul
27        Hernandez Garcia Maria Fernanda
28          Martinez Gonzalez Juan Andres
29              Campos Garcia Juan Carlos
30         Rodriguez Rosales Luis Enrique
31            Rodriguez Esteban Alejandro
32        Solano Sanchez Adriana Gabriela
33          Carrizales Vargas Lucia Maria
34           Ramirez Lopez Maria Fernanda
35          Gonzalez Martinez Juan Andres
36            Orozco Ramirez Pablo Ismael
37               Ojeda Rivera Lucia Maria
38     Covarrubias Murguia Andres Alberto
39             Lopez Ochoa Liliana Isabel
40                    Vidal Lopez Alberto
41       Galvan Magaña Fernanda Alejandra
42             Ochoa Murrieta Juan Andres
43  Gutierrez Magaña Maria De Los Angeles
44                 Odriz Nazario Fernando
45           Magaña Silva Maria Guadalupe
46                Perez Martinez Fernando
47                Nuñez Mejia Pedro Pablo
48                 Silva Sanchez Agustina
49                Garcia Llamas Ana Sofia
50       Hernandez Llamas Lucio Alejandro
51                   Ramos Solano Armando
52         Cardenas Cardenas Ana Patricia
53     Rodriguez Martinez Fernando Javier
54        Sanchez Carrizales Andrea Sofia
55             Torres Vazquez Luis Miguel
56            Lopez Romero Maria Fernanda
57           Sanchez Solano Andres Felipe
58                                 Módulo

In [10]:
df_asignaturas = df['ASIGNATURAS'].str.upper()
df_asignaturas_unicas = df_asignaturas.unique()
df_asignaturas_unicas = pd.DataFrame({'ASIGNATURAS': df_asignaturas_unicas})

In [11]:
df['ASIGNATURAS'] = df_asignaturas
df_asignaturas_unicas

                                          ASIGNATURAS
0                                             ÁLGEBRA
1   APLICA LA METODOLOGÍA DE DESARROLLO RÁPIDO DE ...
2   APLICA LA METODOLOGÍA ESPIRAL CON PROGRAMACIÓN...
3                                            BIOLOGÍA
4                                    CÁLCULO INTEGRAL
5             CIENCIA, TECNOLOGÍA, SOCIEDAD Y VALORES
6      CONSTRUYE BASES DE DATOS PARA APLICACIONES WEB
7   DESARROLLA APLICACIONES WEB CON CONEXIÓN A BAS...
8                    DISEÑA BASES DE DATOS OFIMÁTICAS
9       DISEÑA Y MANTIENE LOS SISTEMAS DE ILUMINACIÓN
10                                              ÉTICA
11                      FABRICA ESTRUCTURAS METÁLICAS
12                                          FÍSICA II
13  GENERA INFORMACIÓN FISCAL DE LAS PERSONAS FÍSICAS
14  GENERA INFORMACIÓN FISCAL DE LAS PERSONAS MORALES
15                                GEOMETRÍA ANALÍTICA
16  GESTIONA INFORMACIÓN MEDIANTE EL USO DE HOJAS ...
17  GESTIONA INFORMACIÓN MEDIANTE EL USO DE PROCES...
18  GESTIONA INFORMACIÓN MEDIANTE EL USO DE SISTEM...
19  GESTIONA INFORMACIÓN MEDIANTE EL USO DE SOFTWA...
20  IMPLEMENTA Y MANTIENE LOS SISTEMAS DE ENERGÍA ...
21                                           INGLÉS I
22                                         INGLÉS III
23                                           INGLÉS V
24                LECTURA, EXPRESIÓN ORAL Y ESCRITA I
25                                             LÓGICA
26                MANTIENE LOS GENERADORES DE CA Y CC
27                    MANTIENE LOS MOTORES DE CA Y CC
28                                          QUÍMICA I
29  REALIZA MANTENIMIENTO A LAS INSTALACIONES ELÉC...
30  REGISTRA INFORMACIÓN CONTABLE EN FORMA ELECTRÓ...
31   REGISTRA INFORMACIÓN DE LOS RECURSOS FINANCIEROS
32    REGISTRA INFORMACIÓN DE LOS RECURSOS MATERIALES
33                   REPARA EQUIPOS DE AUTOMATIZACIÓN
34                         REPARA EQUIPOS HIDRÁULICOS
35                          REPARA EQUIPOS NEUMÁTICOS
36                   SUELDA PIEZAS METÁLICAS FERROSAS
37                SUELDA PIEZAS METÁLICAS NO FERROSAS
38    TECNOLOGÍAS DE LA INFORMACIÓN Y LA COMUNICACIÓN
39  MÓDULO II. APLICA METODOLOGÍAS DE DESARROLLO D...
40    MÓDULO II. GESTIONA INFORMACIÓN DE MANERA LOCAL
41  MÓDULO II. MANTIENE LOS MOTORES Y GENERADORES ...
42  MÓDULO II. OPERA LOS PROCESOS CONTABLES DENTRO...
43  MÓDULO II. SUELDA MATERIALES FERROSOS Y NO FER...
44  MÓDULO IV. DESARROLLA SOFTWARE DE APLICACIÓN W...
45  MÓDULO IV. DETERMINA LAS CONTRIBUCIONES FISCAL...
46  MÓDULO IV. DISEÑA Y GESTIONA BASES DE DATOS OF...
47  MÓDULO IV. DISEÑA Y MANTIENE LOS SISTEMAS DE I...
48  MÓDULO IV. MANTIENE EQUIPOS HIDRÁULICOS, NEUMÁ...

In [12]:
# Cambiar los valores NaN en la columna "HORAS" por el número 0
df["HORAS"].fillna(0, inplace=True)

In [13]:
# Transformar la columna "HORAS" a tipo de dato int
df["HORAS"] = df["HORAS"].astype(int)

In [14]:
df

,DOCENTE,ASIGNATURAS,GRUPO,HORAS,COMPONENTE
0,Garcia Hernandez Luis Eduardo,ÁLGEBRA,1B,4,Asignatura
1,Ramirez Perez Juana Maria,ÁLGEBRA,1F,4,Asignatura
2,Lopez Rodriguez Antonio Manuel,ÁLGEBRA,1A,4,Asignatura
3,Lopez Rodriguez Antonia Maria,ÁLGEBRA,1C,4,Asignatura
4,Lopez Rodriguez Antonia Maria,ÁLGEBRA,1D,4,Asignatura
...,...,...,...,...,...
164,Módulo,MÓDULO IV. DISEÑA Y GESTIONA BASES DE DATOS OF...,5B,0,Módulo
165,Módulo,MÓDULO IV. DISEÑA Y GESTIONA BASES DE DATOS OF...,5F,0,Módulo
166,Módulo,MÓDULO IV. DISEÑA Y MANTIENE LOS SISTEMAS DE I...,5D,0,Módulo
167,Módulo,"MÓDULO IV. MANTIENE EQUIPOS HIDRÁULICOS, NEUMÁ...",5E,0,Módulo
168,Módulo,"MÓDULO IV. MANTIENE EQUIPOS HIDRÁULICOS, NEUMÁ...",5H,0,Módulo

In [15]:
# Agrupar y sumar las horas por docente
horas_por_docente = df.groupby('DOCENTE')['HORAS'].sum().reset_index()

In [16]:
# Ordenar en orden descendente según las horas y restablecer los índices
horas_por_docente = horas_por_docente.sort_values(by='HORAS', ascending=False).reset_index(drop=True)

In [17]:
# Mostrar el DataFrame resultante
print(horas_por_docente)

                                  DOCENTE  HORAS
0       Reyes Rodriguez Esteban Alejandro     31
1                Ojeda Rivera Lucia Maria     31
2                 Nuñez Mejia Pedro Pablo     27
3             Orozco Ramirez Pablo Ismael     25
4            Magaña Silva Maria Guadalupe     25
5         Velazquez Hernandez Maria Elena     24
6                Gonzalez Lopez Ana Luisa     24
7               Campos Garcia Juan Carlos     20
8                   Garcia Alvarez Andres     20
9          Rodriguez Rosales Luis Enrique     20
10            Lopez Ramirez Marco Antonio     20
11        Hernandez Garcia Fabian Enrique     19
12             Lopez Ochoa Liliana Isabel     19
13       Galvan Magaña Fernanda Alejandra     19
14     Covarrubias Murguia Andres Alberto     19
15         Cardenas Cardenas Ana Patricia     18
16            Rodriguez Garcia Ana Carmen     17
17      Verduzco Morales Fabian Alexander     16
18          Martinez Gonzalez Juan Andres     16
19     Rodriguez Martinez Fernando Javier     14
20            Rodriguez Esteban Alejandro     14
21                Perez Martinez Fernando     12
22  Gutierrez Magaña Maria De Los Angeles     12
23       Martinez Villasenor Luis Eduardo     12
24        Solano Sanchez Adriana Gabriela     12
25          Lopez Rodriguez Antonia Maria     12
26                 Silva Sanchez Agustina     11
27         Reyes Rodriguez Antonio Rafael     10
28          Hernandez Reyes Daniela Sofia     10
29         Gutierrez Martinez Pedro Pablo     10
30            Lopez Romero Maria Fernanda      9
31            Velazquez Hernandez Luciana      9
32            Gutierrez Lopez Pedro Pablo      8
33             Ruiz Gutierrez Maria Sofia      8
34        Hernandez Garcia Maria Fernanda      8
35                   Ramos Solano Armando      7
36        Garcia Hernandez Fabian Enrique      5
37        Mendoza Hernandez Jorge Alberto      5
38            Garcia Llamas Liliana Maria      5
39        Rodriguez Alatorre Ana Patricia      4
40           Reyes Rodriguez Antonio Raul      4
41                    Vidal Lopez Alberto      4
42              Ramirez Perez Juana Maria      4
43           Garcia Ruiz Francisco Javier      4
44            Ramirez Lopez Maria Dolores      4
45           Ramirez Gonzalez Pedro Pablo      4
46                 Odriz Nazario Fernando      4
47             Ochoa Murrieta Juan Andres      4
48         Lopez Rodriguez Antonio Manuel      4
49          Carrizales Vargas Lucia Maria      4
50          Garcia Hernandez Luis Eduardo      4
51                Garcia Llamas Ana Sofia      3
52             Torres Vazquez Luis Miguel      3
53        Sanchez Carrizales Andrea Sofia      3
54          Gonzalez Martinez Juan Andres      3
55           Sanchez Solano Andres Felipe      3
56           Ramirez Lopez Maria Fernanda      3
57       Hernandez Llamas Lucio Alejandro      3
58                                 Módulo      0

In [18]:
# Filtrar el DataFrame para el grupo 1F
grupo_1f = df[df['GRUPO'] == '1F'][['ASIGNATURAS', 'DOCENTE']]

grupo_1f

,ASIGNATURAS,DOCENTE
1,ÁLGEBRA,Ramirez Perez Juana Maria
80,INGLÉS I,Orozco Ramirez Pablo Ismael
104,"LECTURA, EXPRESIÓN ORAL Y ESCRITA I",Gonzalez Lopez Ana Luisa
115,LÓGICA,Odriz Nazario Fernando
120,QUÍMICA I,Campos Garcia Juan Carlos
150,TECNOLOGÍAS DE LA INFORMACIÓN Y LA COMUNICACIÓN,Lopez Romero Maria Fernanda

In [27]:
# Filtrar el DataFrame para el docente "Nuñez Mejia Pedro Pablo"
pedro_pablo = df[df['DOCENTE'] == 'Nuñez Mejia Pedro Pablo'][['ASIGNATURAS', 'GRUPO', 'HORAS']]

# Calcular la suma de las horas
total_horas = pedro_pablo['HORAS'].sum()

# Crear un DataFrame con la fila que muestra el total de horas
total_row = pd.DataFrame([['Total Horas', ' ', total_horas]], columns=['ASIGNATURAS', 'GRUPO', 'HORAS'])

# Concatenar el DataFrame original con la fila que muestra el total de horas
pedro_pablo = pd.concat([pedro_pablo, total_row], ignore_index=True)

pedro_pablo

                                         ASIGNATURAS GRUPO  HORAS
0                                          QUÍMICA I    1C      4
1                                          QUÍMICA I    1D      4
2                                          QUÍMICA I    1E      4
3  REALIZA MANTENIMIENTO A LAS INSTALACIONES ELÉC...    5D      4
4  REGISTRA INFORMACIÓN CONTABLE EN FORMA ELECTRÓ...    3G     11
5                                        Total Horas           27